# Generated by Django 5.2.17 on 2026-08-25 07:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommandSeq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Terminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "terminal_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("serial_number", models.CharField(max_length=255, unique=True)),
                ("identity", models.JSONField(default=dict)),
                ("last_heartbeat", models.JSONField(blank=True, null=True)),
                ("last_inventory", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command_id", models.CharField(max_length=64, unique=True)),
                ("type", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("issued_at", models.BigIntegerField()),
                ("expires_at", models.BigIntegerField()),
                ("status", models.CharField(default="pending", max_length=32)),
                ("result", models.JSONField(blank=True, null=True)),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="core.terminal",
                    ),
                ),
            ],
            options={
                "ordering": ["issued_at", "id"],
            },
        ),
    ]
