# Generated by Django 5.2.17 on 2026-09-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TerminalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command_id", models.CharField(blank=True, default="", max_length=64)),
                ("kind", models.CharField(max_length=64)),
                ("level", models.CharField(default="info", max_length=16)),
                ("message", models.TextField()),
                ("meta", models.JSONField(default=dict)),
                ("event_at", models.BigIntegerField()),
                ("received_at", models.BigIntegerField()),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.terminal",
                    ),
                ),
            ],
            options={
                "ordering": ["event_at", "id"],
            },
        ),
    ]
