# Generated by Django 5.2.8 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_terminalevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="terminal",
            name="last_location",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
